  package GUI;

import OOP.Employee;
import javax.swing.JFrame;
import javax.swing.JTextField;
import OOP.InputValidator;
import OOP.ValidationRule;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class EmployeePortal extends javax.swing.JFrame {
    private Employee currentEmployee;
    
    //This is needed so the encapsulation in employee.java is respected :)
    public void fillEmployeeDetails(Employee employee) {
        this.currentEmployee = employee;
        String[] details = employee.getDetails();

        lastNameField.setText(details[0]);
        firstNameField.setText(details[1]);
        birthdayField.setText(details[2]);
        statusField.setText(details[3]);
        contactField.setText(details[4]);
        addressField.setText(details[5]);
        basicSalaryField.setText(details[6]);
        hourlyRateField.setText(details[7]);
        riceSubField.setText(details[8]);
        phoneSubField.setText(details[9]);
        clothingField.setText(details[10]);
        sssField.setText(details[11]);
        pagIbigField.setText(details[12]);
        philHealthField.setText(details[13]);
        tinField.setText(details[14]);
        empNumField.setText(details[15]);
        
    }
    
    /**
     * Load employee details using service layer.
     * @param employeeId the employee ID
     */
    public void loadEmployeeDetails(String employeeId) {
        try {
            CTRL_SRVS.EmployeeService employeeService = new CTRL_SRVS.EmployeeService();
            Employee employee = employeeService.getEmployeeDetails(employeeId);
            if (employee != null) {
                fillEmployeeDetails(employee);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Employee not found: " + employeeId, 
                                                           "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading employee details: " + e.getMessage(), 
                                                       "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public EmployeePortal() {
        initComponents();
        Map<java.awt.Component, ValidationRule> rules = new HashMap<>();
        
        // Required fields
        rules.put(empNumField, ValidationRule.REQUIRED);
        rules.put(lastNameField, ValidationRule.REQUIRED);
        rules.put(firstNameField, ValidationRule.REQUIRED);
        rules.put(statusField, ValidationRule.REQUIRED);

        // Format validations
        rules.put(empNumField, ValidationRule.EMPLOYEE_ID);
        rules.put(lastNameField, ValidationRule.NAME);
        rules.put(firstNameField, ValidationRule.NAME);
        rules.put(sssField, ValidationRule.SSS);
        rules.put(philHealthField, ValidationRule.PHILHEALTH);
        rules.put(tinField, ValidationRule.TIN);
        rules.put(pagIbigField, ValidationRule.PAGIBIG);
        rules.put(contactField, ValidationRule.PHONE);
        rules.put(birthdayField, ValidationRule.DATE_YYYYMMDD);
        rules.put(addressField, ValidationRule.GENERIC_TEXT);

        // Numeric fields
        rules.put(basicSalaryField, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(hourlyRateField, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(riceSubField, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(phoneSubField, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(clothingField, ValidationRule.DECIMAL_NON_NEGATIVE);

        // Validate
        String error = InputValidator.validate(rules);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")//generated code below, do not touch
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogOutButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactField = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        statusField = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        birthdayField = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        lastNameField = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        firstNameField = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        empNumField = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        basicSalaryField = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        hourlyRateField = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        riceSubField = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        phoneSubField = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        clothingField = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        sssField = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        pagIbigField = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        philHealthField = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        tinField = new javax.swing.JTextPane();
        requestLeaveButton = new javax.swing.JButton();
        viewPayslipButton = new javax.swing.JButton();
        timeOut = new javax.swing.JButton();
        timeIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(176, 196, 222));

        LogOutButton.setBackground(new java.awt.Color(54, 117, 136));
        LogOutButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setText("Log Out");
        LogOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(54, 117, 136));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE PORTAL");
        jLabel2.setToolTipText("");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERSONAL INFORMATION");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 228, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel6.setText("Birthday:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, -1));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel9.setText("Contact #:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel10.setText("Current address: ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, -1, -1));

        addressField.setEditable(false);
        addressField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(addressField);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 90));

        contactField.setEditable(false);
        contactField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(contactField);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, -1));

        statusField.setEditable(false);
        statusField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(statusField);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, -1));

        birthdayField.setEditable(false);
        birthdayField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(birthdayField);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        lastNameField.setEditable(false);
        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(lastNameField);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, -1));

        firstNameField.setEditable(false);
        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setViewportView(firstNameField);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, -1));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel8.setText("Number:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        empNumField.setEditable(false);
        empNumField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane17.setViewportView(empNumField);

        jPanel4.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SALARY INFORMATION");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel12.setText("Basic salary:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel13.setText("Hourly rate: ");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 90, -1));

        jLabel14.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel14.setText("Rice subsidy:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, -1));

        jLabel15.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel15.setText("Phone subsidy:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        jLabel16.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel16.setText("Clothing:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, -1));

        basicSalaryField.setEditable(false);
        basicSalaryField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(basicSalaryField);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, -1));

        hourlyRateField.setEditable(false);
        hourlyRateField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane9.setViewportView(hourlyRateField);

        jPanel5.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 90, -1));

        riceSubField.setEditable(false);
        riceSubField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane10.setViewportView(riceSubField);

        jPanel5.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, -1));

        phoneSubField.setEditable(false);
        phoneSubField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane11.setViewportView(phoneSubField);

        jPanel5.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

        clothingField.setEditable(false);
        clothingField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane12.setViewportView(clothingField);

        jPanel5.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DEDUCTIONS");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel18.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel18.setText("SSS contribution:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel19.setText("Pag-Ibig: ");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel20.setText("Phil-Health:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel21.setText("TIN:");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        sssField.setEditable(false);
        sssField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane13.setViewportView(sssField);

        jPanel6.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 267, 30));

        pagIbigField.setEditable(false);
        pagIbigField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane14.setViewportView(pagIbigField);

        jPanel6.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 267, 30));

        philHealthField.setEditable(false);
        philHealthField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane15.setViewportView(philHealthField);

        jPanel6.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 267, 30));

        tinField.setEditable(false);
        tinField.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane16.setViewportView(tinField);

        jPanel6.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 267, 30));

        requestLeaveButton.setBackground(new java.awt.Color(176, 196, 222));
        requestLeaveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        requestLeaveButton.setText("Request Leave");
        requestLeaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestLeaveButton.setMaximumSize(new java.awt.Dimension(85, 20));
        requestLeaveButton.setMinimumSize(new java.awt.Dimension(85, 20));
        requestLeaveButton.setPreferredSize(new java.awt.Dimension(85, 20));
        requestLeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLeaveButtonActionPerformed(evt);
            }
        });

        viewPayslipButton.setBackground(new java.awt.Color(176, 196, 222));
        viewPayslipButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewPayslipButton.setText("View Payslip");
        viewPayslipButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewPayslipButton.setMaximumSize(new java.awt.Dimension(85, 20));
        viewPayslipButton.setMinimumSize(new java.awt.Dimension(85, 20));
        viewPayslipButton.setPreferredSize(new java.awt.Dimension(85, 20));
        viewPayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPayslipButtonActionPerformed(evt);
            }
        });

        timeOut.setBackground(new java.awt.Color(176, 196, 222));
        timeOut.setText("Time-Out");
        timeOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOutActionPerformed(evt);
            }
        });

        timeIn.setBackground(new java.awt.Color(176, 196, 222));
        timeIn.setText("Time-In");
        timeIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(requestLeaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewPayslipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(timeIn)
                                .addGap(18, 18, 18)
                                .addComponent(timeOut)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestLeaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPayslipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeIn)
                            .addComponent(timeOut))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestLeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLeaveButtonActionPerformed
         LeaveReqPortal leaveWindow = new LeaveReqPortal(currentEmployee); 
         leaveWindow.setVisible(true);
    }//GEN-LAST:event_requestLeaveButtonActionPerformed

    private void viewPayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPayslipButtonActionPerformed
    String employeeID = empNumField.getText().trim();
    PayslipPopup popup = new PayslipPopup(employeeID);
    popup.setVisible(true);
    }//GEN-LAST:event_viewPayslipButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed

        LogIn frame = new LogIn();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void timeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInActionPerformed
        try {
            if (currentEmployee == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No employee loaded", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String empId = currentEmployee.getEmployeeNumber();
            String date = getCurrentDate();
            String timeIn = getCurrentTime();
            
            DAO.AttendanceDAO attendanceDAO = new DAO.AttendanceDAO();
            attendanceDAO.logAttendance(empId, date, timeIn, "");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Time-In recorded successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error recording time-in: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_timeInActionPerformed

    private void timeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOutActionPerformed
        try {
            if (currentEmployee == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No employee loaded", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String empId = currentEmployee.getEmployeeNumber();
            String date = getCurrentDate();
            String timeOut = getCurrentTime();
            
            DAO.AttendanceDAO attendanceDAO = new DAO.AttendanceDAO();
            attendanceDAO.logAttendance(empId, date, "", timeOut);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Time-Out recorded successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error recording time-out: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_timeOutActionPerformed

    // Helper methods for date/time
    private String getCurrentDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        return today.toString(); // YYYY-MM-DD format
    }

    private String getCurrentTime() {
        java.time.LocalTime now = java.time.LocalTime.now();
        // Remove nanoseconds for cleaner CSV format
        return now.truncatedTo(java.time.temporal.ChronoUnit.SECONDS).toString(); // HH:MM:SS format
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    public javax.swing.JTextPane addressField;
    public javax.swing.JTextPane basicSalaryField;
    public javax.swing.JTextPane birthdayField;
    public javax.swing.JTextPane clothingField;
    public javax.swing.JTextPane contactField;
    public javax.swing.JTextPane empNumField;
    public javax.swing.JTextPane firstNameField;
    public javax.swing.JTextPane hourlyRateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTextPane lastNameField;
    public javax.swing.JTextPane pagIbigField;
    public javax.swing.JTextPane philHealthField;
    public javax.swing.JTextPane phoneSubField;
    private javax.swing.JButton requestLeaveButton;
    public javax.swing.JTextPane riceSubField;
    public javax.swing.JTextPane sssField;
    public javax.swing.JTextPane statusField;
    private javax.swing.JButton timeIn;
    private javax.swing.JButton timeOut;
    public javax.swing.JTextPane tinField;
    private javax.swing.JButton viewPayslipButton;
    // End of variables declaration//GEN-END:variables
}
