/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import OOP.Admin;
import OOP.SystemIT;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import OOP.SessionTimeoutManager;
import OOP.InputValidator;
import OOP.ValidationRule;
import java.util.HashMap;
import java.util.Map;
import CTRL_SRVS.PasswordService;
import CTRL_SRVS.EmployeeService;
import DAO.EmployeeDAO;

/**
 *
 * @author Ira
 */
public class HRPortal extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInfoPortal
     */
    // Temporary storage for original passwords to enable showing them
    private String originalPassword = "";
    private PasswordService passwordService;
    
    public HRPortal() {
        initComponents();
        // Initialize PasswordService
        this.passwordService = new PasswordService();
        //Call timeout
        SessionTimeoutManager.start(this, () -> {
        // This runs on Swing EDT — safe to show dialogs and dispose
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Session timed out due to inactivity.",
                "Session Expired",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            new GUI.LogIn().setVisible(true); // Assuming Login is in GUI package
            this.dispose();
        });
        
        // Load employee data automatically on HR login
        loadEmployeeDataOnStartup();
    }
        @Override
    public void dispose() {
        SessionTimeoutManager.stop(); // Explicit cleanup
        super.dispose();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        showInfo = new javax.swing.JButton();
        GovDetailPane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sss = new javax.swing.JTextField();
        tin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pagIBIG = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        philHealth = new javax.swing.JTextField();
        PayrollPane = new javax.swing.JPanel();
        basicSalary = new javax.swing.JTextField();
        riceSub = new javax.swing.JTextField();
        hourlyRate = new javax.swing.JTextField();
        clothingAllowance = new javax.swing.JTextField();
        monthlyRate = new javax.swing.JTextField();
        phoneAllowance = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        FinerDetailPane = new javax.swing.JPanel();
        address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        birthday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        position = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        immediateSupervisor = new javax.swing.JTextField();
        empNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CredentialsPane = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 117, 136));

        updateTable.setBackground(new java.awt.Color(242, 242, 242));
        updateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Last Name", "First Name", "SSS #", "PhilHealth #", "TIN #", "Pag IBIG #", "Birthday", "Address", "Phone Number", "Status", "Position", "Immediate Supervisor", "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", "Gross Semi-Monthly Rate", "Hourly Rate", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        updateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(updateTable);
        if (updateTable.getColumnModel().getColumnCount() > 0) {
            updateTable.getColumnModel().getColumn(0).setResizable(false);
            updateTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            updateTable.getColumnModel().getColumn(3).setMinWidth(0);
            updateTable.getColumnModel().getColumn(3).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(3).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(4).setMinWidth(0);
            updateTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(4).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(5).setMinWidth(0);
            updateTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(5).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(6).setMinWidth(0);
            updateTable.getColumnModel().getColumn(6).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(6).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(8).setMinWidth(0);
            updateTable.getColumnModel().getColumn(8).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(8).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(13).setMinWidth(0);
            updateTable.getColumnModel().getColumn(13).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(13).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(14).setMinWidth(0);
            updateTable.getColumnModel().getColumn(14).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(14).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(15).setMinWidth(0);
            updateTable.getColumnModel().getColumn(15).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(15).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(16).setMinWidth(0);
            updateTable.getColumnModel().getColumn(16).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(16).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(17).setMinWidth(0);
            updateTable.getColumnModel().getColumn(17).setPreferredWidth(0);
            updateTable.getColumnModel().getColumn(17).setMaxWidth(0);
            updateTable.getColumnModel().getColumn(20).setResizable(false);
        }

        jSeparator1.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(54, 117, 136));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Employee Number/Last name/First name");

        logOut.setBackground(new java.awt.Color(176, 196, 222));
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(175, 196, 222));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(176, 196, 222));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(176, 196, 222));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        showInfo.setBackground(new java.awt.Color(176, 196, 222));
        showInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showInfo.setText("Show Information");
        showInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(showInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOut)
                    .addComponent(refresh))
                .addGap(15, 15, 15))
        );

        GovDetailPane.setBackground(new java.awt.Color(54, 117, 136));
        GovDetailPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SSS Number:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TIN Number:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PagIBIG Number:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PhilHealth Number:");

        javax.swing.GroupLayout GovDetailPaneLayout = new javax.swing.GroupLayout(GovDetailPane);
        GovDetailPane.setLayout(GovDetailPaneLayout);
        GovDetailPaneLayout.setHorizontalGroup(
            GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GovDetailPaneLayout.createSequentialGroup()
                .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GovDetailPaneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(8, 8, 8)
                        .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tin, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(sss)))
                    .addGroup(GovDetailPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(philHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GovDetailPaneLayout.setVerticalGroup(
            GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GovDetailPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(philHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GovDetailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(pagIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PayrollPane.setBackground(new java.awt.Color(54, 117, 136));
        PayrollPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        basicSalary.setEditable(false);

        riceSub.setEditable(false);
        riceSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceSubActionPerformed(evt);
            }
        });

        hourlyRate.setEditable(false);
        hourlyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateActionPerformed(evt);
            }
        });

        clothingAllowance.setEditable(false);

        monthlyRate.setEditable(false);

        phoneAllowance.setEditable(false);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Gross Semi-Monthly Rate:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone Allowance:");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Clothing Allowance:");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Rice Subsidy:");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Basic Salary:");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hourly Rate:");

        javax.swing.GroupLayout PayrollPaneLayout = new javax.swing.GroupLayout(PayrollPane);
        PayrollPane.setLayout(PayrollPaneLayout);
        PayrollPaneLayout.setHorizontalGroup(
            PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayrollPaneLayout.createSequentialGroup()
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(riceSub)
                    .addComponent(basicSalary)
                    .addComponent(clothingAllowance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneAllowance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monthlyRate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hourlyRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        PayrollPaneLayout.setVerticalGroup(
            PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayrollPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riceSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(PayrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FinerDetailPane.setBackground(new java.awt.Color(54, 117, 136));
        FinerDetailPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));
        FinerDetailPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FinerDetailPane.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 193, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");
        FinerDetailPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");
        FinerDetailPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 13, 77, -1));
        FinerDetailPane.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 8, 120, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Surname:");
        FinerDetailPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        FinerDetailPane.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Birthday:");
        FinerDetailPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 48, -1, -1));
        FinerDetailPane.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 48, 120, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No:");
        FinerDetailPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        FinerDetailPane.add(phoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status:");
        FinerDetailPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, -1, -1));
        FinerDetailPane.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 88, 120, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Position:");
        FinerDetailPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        FinerDetailPane.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Immediate Supervisor:");
        FinerDetailPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));
        FinerDetailPane.add(immediateSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 193, 30));

        empNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumActionPerformed(evt);
            }
        });
        FinerDetailPane.add(empNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 193, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee No.:");
        FinerDetailPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        CredentialsPane.setBackground(new java.awt.Color(54, 117, 136));
        CredentialsPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CredentialsPaneLayout = new javax.swing.GroupLayout(CredentialsPane);
        CredentialsPane.setLayout(CredentialsPaneLayout);
        CredentialsPaneLayout.setHorizontalGroup(
            CredentialsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CredentialsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CredentialsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        CredentialsPaneLayout.setVerticalGroup(
            CredentialsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CredentialsPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FinerDetailPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GovDetailPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(PayrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CredentialsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PayrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(GovDetailPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FinerDetailPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(CredentialsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(54, 117, 136));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Welcome, Admin!");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setForeground(new java.awt.Color(176, 196, 222));
        jLabel25.setText("You can now manage, edit, and update employee records efficiently.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumActionPerformed

    private void hourlyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateActionPerformed

    private void riceSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceSubActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        try {
            // Use service layer to load employee data
            EmployeeService employeeService = new EmployeeService();
            String[][] employeeData = employeeService.loadEmployeeDataFromCSV(SystemIT.EMPLOYEE_CSV);
            
            // Clear and populate table
            DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
            model.setRowCount(0);
            
            for (String[] rowData : employeeData) {
                model.addRow(rowData);
            }
            
            // Show confirmation message
            JOptionPane.showMessageDialog(this, "Employee details were refreshed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to load employee data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * Validates employee data using comprehensive validation rules.
     * This method is shared between create and update operations to ensure consistency.
     * 
     * @return null if validation passes, error message string if validation fails
     */
    private String validateEmployeeData() {
        Map<javax.swing.JTextField, ValidationRule> rules = new HashMap<>();
        
        // Required fields validation - these must always be filled
        rules.put(empNum, ValidationRule.REQUIRED);
        rules.put(lastName, ValidationRule.REQUIRED);
        rules.put(firstName, ValidationRule.REQUIRED);
        rules.put(position, ValidationRule.REQUIRED);
        rules.put(status, ValidationRule.REQUIRED);
        rules.put(phoneNum, ValidationRule.REQUIRED);
        rules.put(sss, ValidationRule.REQUIRED);
        
        // Format validation (applied only if field is not empty)
        rules.put(empNum, ValidationRule.EMPLOYEE_ID);
        rules.put(lastName, ValidationRule.NAME);
        rules.put(firstName, ValidationRule.NAME);
        rules.put(sss, ValidationRule.SSS);
        rules.put(philHealth, ValidationRule.PHILHEALTH);
        rules.put(tin, ValidationRule.TIN);
        rules.put(pagIBIG, ValidationRule.PAGIBIG);
        rules.put(phoneNum, ValidationRule.PHONE);
        rules.put(birthday, ValidationRule.DATE_YYYYMMDD);
        rules.put(address, ValidationRule.GENERIC_TEXT);
        rules.put(immediateSupervisor, ValidationRule.NAME);
        
        // Number validation (applied only if field is not empty)
        rules.put(basicSalary, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(riceSub, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(phoneAllowance, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(clothingAllowance, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(monthlyRate, ValidationRule.DECIMAL_NON_NEGATIVE);
        rules.put(hourlyRate, ValidationRule.DECIMAL_NON_NEGATIVE);
        
        // Validation checker
        return InputValidator.validate(rules);
    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Use HR-specific validation method
        String error = validateHRData();
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Admin admin = new Admin("", "");

        JTextField[] textFields = {
            empNum, lastName, firstName, sss, philHealth,
            tin, pagIBIG, birthday, address, phoneNum,
            status, position, immediateSupervisor, basicSalary, riceSub,
            phoneAllowance, clothingAllowance, monthlyRate, hourlyRate,
            emailTextField
        };

        admin.updateEmployeeDetails(updateTable, textFields, emailTextField, null);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
        // Get the search term from the text field
        String searchTerm = search.getText().trim();

        // Check if the search term is not empty
        if (!searchTerm.isEmpty()) {

            boolean found = false;
            // Iterate through the rows of the table model
            for (int i = 0; i < model.getRowCount(); i++) {

                // Get the employee number, last name, and first name from the current row
                String empNumber = model.getValueAt(i, 0).toString();
                String lastName = model.getValueAt(i, 1).toString();
                String firstName = model.getValueAt(i, 2).toString();

                // Check if the search term matches any of the employee details
                if (empNumber.equalsIgnoreCase(searchTerm) ||
                    lastName.equalsIgnoreCase(searchTerm) ||
                    firstName.equalsIgnoreCase(searchTerm)) {

                    // Select the matching row in the table and scroll to it
                    updateTable.getSelectionModel().setSelectionInterval(i, i);
                    updateTable.scrollRectToVisible(updateTable.getCellRect(i, 0, true));
                    found = true;
                    break;
                }
            }

            // Show a message if no matching employee is found
            if (!found) {
                JOptionPane.showMessageDialog(this, "Employee not found!", "Search Result", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Show a warning message if the search term is empty
            JOptionPane.showMessageDialog(this, "Please enter a term to search", "Search Result", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        LogIn frame1 = new LogIn();
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutActionPerformed

    
    private void updateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTableMouseClicked
        Admin admin = new Admin("", "");

        JTextField[] textFields = {
            empNum, lastName, firstName, sss, philHealth,
            tin, pagIBIG, birthday, address, phoneNum,
            status, position, immediateSupervisor, basicSalary, riceSub,
            phoneAllowance, clothingAllowance, monthlyRate, hourlyRate,
            emailTextField
        };

        admin.populateFieldsFromTable(updateTable, textFields, emailTextField, null);
    }//GEN-LAST:event_updateTableMouseClicked

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void showInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfoActionPerformed
        // Get the table model
        DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
        
        // Check if any row is selected
        int selectedRow = updateTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an employee from the table first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Create and populate ViewInformation form
            ViewInformation viewInfo = new ViewInformation();
            
            // Populate employee basic information
            viewInfo.employeeNumber.setText(model.getValueAt(selectedRow, 0).toString()); // Employee Number
            viewInfo.lastName.setText(model.getValueAt(selectedRow, 1).toString()); // Last Name
            viewInfo.firstName.setText(model.getValueAt(selectedRow, 2).toString()); // First Name
            viewInfo.birthday.setText(model.getValueAt(selectedRow, 7).toString()); // Birthday
            viewInfo.address.setText(model.getValueAt(selectedRow, 8).toString()); // Address
            viewInfo.phoneNumber.setText(model.getValueAt(selectedRow, 9).toString()); // Phone Number
            
            // Populate job details
            viewInfo.status.setText(model.getValueAt(selectedRow, 10).toString()); // Status
            viewInfo.position.setText(model.getValueAt(selectedRow, 11).toString()); // Position
            viewInfo.immediateSupervisor.setText(model.getValueAt(selectedRow, 12).toString()); // Immediate Supervisor
            
            // Populate government IDs
            viewInfo.sss.setText(model.getValueAt(selectedRow, 3).toString()); // SSS
            viewInfo.philHealth.setText(model.getValueAt(selectedRow, 4).toString()); // PhilHealth
            viewInfo.tin.setText(model.getValueAt(selectedRow, 5).toString()); // TIN
            viewInfo.pagIBIG.setText(model.getValueAt(selectedRow, 6).toString()); // PagIBIG
            
            // Populate compensation details
            viewInfo.basicSalary.setText(model.getValueAt(selectedRow, 13).toString()); // Basic Salary
            viewInfo.riceSub.setText(model.getValueAt(selectedRow, 14).toString()); // Rice Subsidy
            viewInfo.phoneAllowance.setText(model.getValueAt(selectedRow, 15).toString()); // Phone Allowance
            viewInfo.clothingAllowance.setText(model.getValueAt(selectedRow, 16).toString()); // Clothing Allowance
            viewInfo.monthlyRate.setText(model.getValueAt(selectedRow, 17).toString()); // Gross Semi-Monthly Rate
            viewInfo.hourlyRate.setText(model.getValueAt(selectedRow, 18).toString()); // Hourly Rate
            
            // Make the ViewInformation form visible
            viewInfo.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error displaying employee information: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_showInfoActionPerformed


    /**
     * Loads employee data automatically when HR logs in.
     * This method is called from the constructor to populate the table.
     */
    private void loadEmployeeDataOnStartup() {
        try {
            // Use service layer to load employee data
            EmployeeService employeeService = new EmployeeService();
            String[][] employeeData = employeeService.loadEmployeeDataFromCSV(SystemIT.EMPLOYEE_CSV);
            
            // Clear and populate table
            DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
            model.setRowCount(0);
            
            for (String[] rowData : employeeData) {
                model.addRow(rowData);
            }
            
            // Show confirmation message only if data was loaded successfully
            if (employeeData.length > 0) {
                System.out.println("Employee data loaded successfully on HR login.");
            }
            
        } catch (Exception e) {
            // Don't show error message on startup, just log it
            System.err.println("Failed to load employee data on startup: " + e.getMessage());
            // The user can still use the refresh button to manually load data
        }
    }
    
    /**
     * Validates employee data for HR role - only validates fields HR can edit.
     * HR can only edit: names, address, status, position, and government numbers.
     * 
     * @return null if validation passes, error message string if validation fails
     */
    private String validateHRData() {
        Map<javax.swing.JTextField, ValidationRule> rules = new HashMap<>();
        
        // Required fields validation - these must always be filled
        rules.put(empNum, ValidationRule.REQUIRED);
        rules.put(lastName, ValidationRule.REQUIRED);
        rules.put(firstName, ValidationRule.REQUIRED);
        rules.put(position, ValidationRule.REQUIRED);
        rules.put(status, ValidationRule.REQUIRED);
        rules.put(sss, ValidationRule.REQUIRED);
        
        // Format validation (applied only if field is not empty)
        rules.put(empNum, ValidationRule.EMPLOYEE_ID);
        rules.put(lastName, ValidationRule.NAME);
        rules.put(firstName, ValidationRule.NAME);
        rules.put(sss, ValidationRule.SSS);
        rules.put(philHealth, ValidationRule.PHILHEALTH);
        rules.put(tin, ValidationRule.TIN);
        rules.put(pagIBIG, ValidationRule.PAGIBIG);
        rules.put(phoneNum, ValidationRule.PHONE);
        rules.put(birthday, ValidationRule.DATE_YYYYMMDD);
        rules.put(address, ValidationRule.GENERIC_TEXT);
        rules.put(immediateSupervisor, ValidationRule.NAME);
        
        // Validation checker
        return InputValidator.validate(rules);
    }
    
    /**
     * Generates a system password for new employees using the pattern: EMP{EmployeeID}{Random4Digits}
     * This method is kept for backward compatibility, but PasswordService should be used instead.
     * 
     * @param employeeId The employee ID to use in password generation
     * @return Generated password string
     */
    private String generatePassword(String employeeId) {
        // Generate 4 random digits
        int randomDigits = (int) (Math.random() * 9000) + 1000; // Ensures 4 digits (1000-9999)
        
        // Create password using the required pattern
        String rawPassword = "EMP" + employeeId + randomDigits;
        
        return rawPassword;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CredentialsPane;
    private javax.swing.JPanel FinerDetailPane;
    private javax.swing.JPanel GovDetailPane;
    private javax.swing.JPanel PayrollPane;
    private javax.swing.JTextField address;
    private javax.swing.JTextField basicSalary;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField clothingAllowance;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField empNum;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField hourlyRate;
    private javax.swing.JTextField immediateSupervisor;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField monthlyRate;
    private javax.swing.JTextField pagIBIG;
    private javax.swing.JTextField philHealth;
    private javax.swing.JTextField phoneAllowance;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTextField position;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField riceSub;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showInfo;
    private javax.swing.JTextField sss;
    private javax.swing.JTextField status;
    private javax.swing.JTextField tin;
    private javax.swing.JButton updateButton;
    public javax.swing.JTable updateTable;
    // End of variables declaration//GEN-END:variables
}
